
package tr.gov.turkiye.standart.universite.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UniversiteStandartPortType", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UniversiteStandartPortType {


    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.OgrenciBilgisiListesiSorgulamaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/ogrenciBilgisiSorgula")
    @WebResult(name = "ogrenciBilgisiSorgulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public OgrenciBilgisiListesiSorgulamaCType ogrenciBilgisiSorgula(
        @WebParam(name = "ogrenciBilgisiSorgulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        OgrencilikBilgisiSorgulamaGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.DonemNotOrtalamasiCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/donemNotOrtalamasiSorgula")
    @WebResult(name = "donemNotOrtalamasiC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public DonemNotOrtalamasiCType donemNotOrtalamasiSorgula(
        @WebParam(name = "donemNotOrtalamasiG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        DonemNotOrtalamasiGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.DanismanBilgisiSorgulamaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/danismanBilgisiSorgula")
    @WebResult(name = "danismanBilgisiSorgulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public DanismanBilgisiSorgulamaCType danismanBilgisiSorgula(
        @WebParam(name = "danismanBilgisiSorgulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        DanismanBilgisiSorgulamaGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.UniversiteBelgeOlusturCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/universiteBelgeOlustur")
    @WebResult(name = "universiteBelgeOlusturC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public UniversiteBelgeOlusturCType universiteBelgeOlustur(
        @WebParam(name = "universiteBelgeOlusturG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        UniversiteBelgeOlusturGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.KayitliBelgeSorgulaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/kayitliBelgeSorgula")
    @WebResult(name = "kayitliBelgeSorgulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public KayitliBelgeSorgulaCType kayitliBelgeSorgula(
        @WebParam(name = "kayitliBelgeSorgulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        KayitliBelgeSorgulaGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.BarkodluBelgeDogrulaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/barkodluBelgeDogrulama")
    @WebResult(name = "barkodluBelgeDogrulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public BarkodluBelgeDogrulaCType barkodluBelgeDogrulama(
        @WebParam(name = "barkodluBelgeDogrulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        BarkodluBelgeDogrulaGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.AkademikTakvimCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/akademikTakvim")
    @WebResult(name = "akademikTakvimC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public AkademikTakvimCType akademikTakvim(
        @WebParam(name = "akademikTakvimG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        SorguParametreType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.SinavSonucuCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/sinavSonucuSorgula")
    @WebResult(name = "sinavSonucuC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public SinavSonucuCType sinavSonucuSorgula(
        @WebParam(name = "sinavSonucuG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        SinavSonucuGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.AyarOkuCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/ayarOku")
    @WebResult(name = "ayarOkuC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public AyarOkuCType ayarOku(
        @WebParam(name = "ayarOkuG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        AyarOkuGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.AyarOkuListeCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/ayarOkuListe")
    @WebResult(name = "ayarOkuListeC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public AyarOkuListeCType ayarOkuListe(
        @WebParam(name = "ayarOkuListeG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        AyarOkuGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.EtkinlikBilgisiSorgulaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/etkinlikBilgisiSorgula")
    @WebResult(name = "etkinlikBilgisiSorgulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public EtkinlikBilgisiSorgulaCType etkinlikBilgisiSorgula(
        @WebParam(name = "etkinlikBilgisiSorgulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        SorguParametreType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.DilSorgulaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/dilSorgula")
    @WebResult(name = "dilSorgulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public DilSorgulaCType dilSorgula(
        @WebParam(name = "dilSorgulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        DilSorgulaGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.DevamTakipBilgisiSorgulamaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/devamTakipBilgisiSorgula")
    @WebResult(name = "devamTakipBilgisiSorgulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public DevamTakipBilgisiSorgulamaCType devamTakipBilgisiSorgula(
        @WebParam(name = "devamTakipBilgisiSorgulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        DevamTakipBilgisiSorgulamaGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.SertifikaSorgulaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/sertifikaSorgula")
    @WebResult(name = "sertifikaSorgulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public SertifikaSorgulaCType sertifikaSorgula(
        @WebParam(name = "sertifikaSorgulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        KisiselSorgulamaGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.SertifikaBelgeIndirCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/sertifikaBelgeIndir")
    @WebResult(name = "sertifikaBelgeIndirC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public SertifikaBelgeIndirCType sertifikaBelgeIndir(
        @WebParam(name = "sertifikaBelgeIndirG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        SertifikaBelgeIndirGType part1);

    /**
     * 
     * @param part1
     * @return
     *     returns tr.gov.turkiye.standart.universite.v3.DonemSorgulaCType
     */
    @WebMethod(action = "http://standart.turkiye.gov.tr/universite/v3/donemSorgula")
    @WebResult(name = "donemSorgulaC", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
    public DonemSorgulaCType donemSorgula(
        @WebParam(name = "donemSorgulaG", targetNamespace = "http://standart.turkiye.gov.tr/universite/v3", partName = "part1")
        DonemSorgulaGType part1);

}
